### PR TITLE
Update 7.3 Prod branch to latest Apicurito upstream code

### PR DESCRIPTION
**Pull request by EricWittmann**
I have pulled in the latest changes from apicurito upstream, and then cherry-picked the two prod-specific commits (a change to slf4j version, and an update to `ui/pom.xml`).

### CODE REVIEW

**Comment by janstey** [comment]
@orpiske @djcoleman @cunningt this look OK to you guys?

**Comment by cunningt** [comment]
This looks like it might have been based off the wrong branch.

**Comment by orpiske** [comment]
> @orpiske @djcoleman @cunningt this look OK to you guys?

Quite a bit more changes that I was expecting, TBH.

**Comment by EricWittmann** [comment]
So a few questions/comments then:

1) When is 7.3 going to be released?
2) Does 7.3 include the upgrade to the Patternfly 4 masthead for all UIs?
3) The diff includes an upgrade to Angular 7 (from Angular 5) which accounts for some of the changes
4) The diff includes the new helm-charts operator (maybe it shouldn't?)

I may have made incorrect assumptions about what we want released in 7.3...

**Comment by janstey** [comment]
Looping in @paoloantinori @alexkieling here because I'm not sure what UI component versions we are using everywhere else.

**Comment by gashcrumb** [comment]
> When is 7.3 going to be released?

Soon?  AFAIK we're still producing CR builds but yes, really soon.

> Does 7.3 include the upgrade to the Patternfly 4 masthead for all UIs?

It should yes.  Obviously for the embedded version in Syndesis this is a non-issue, but yeah, the standalone editor would need the updated masthead.

> The diff includes an upgrade to Angular 7 (from Angular 5) which accounts for some of the changes

This wouldn't have an impact on anything other than apicurito I imagine since it's standalone, are there big look and feel differences between the console here and the one that's embedded in the Syndesis UI with this change?

**Comment by EricWittmann** [comment]
OK based on the @gashcrumb's response I think I have done the right thing with this PR.  In order to get the PF4 masthead done more easily I decided to upgrade to angular 7.  And yes, that shouldn't affect anything except standalone Apicurito.

The masthead change and the addition of the operator accounts for the majority of the changes, TBH.  And I think QE has been testing the upstream docker image (which is basically this PR)... so I think we're ok there.

**Comment by EricWittmann** [comment]
Bottom line:  my opinion is that this PR is necessary for the 7.3 release.  :)

Despite the unexpectedly large number of files in the diff...

**Comment by orpiske** [comment]
Thanks for the explanation! Based on that, I think we should be good to go. Let's approve the PR and rebuild the images for this.

**Review by janstey — APPROVED** [review]
:+1:

**Pull request merged**
